rangeland/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from djgeojson.views import TiledGeoJSONLayerView
from grazing.models import Health

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rangeland.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'grazing.views.index', name='index'),
        url(r'^allotments/(?P<allotment_unique>.*)/$', 'grazing.views.allotment', name='allotment'),
        url(r'^states/(?P<state_slug>.*)/$', 'grazing.views.state', name='state'),
    # url(r'^data/(?P<z>\d+)/(?P<x>\d+)/(?P<y>\d+).geojson$', TiledGeoJSONLayerView.as_view(model=Health), name='data'),


    url(r'^admin/', include(admin.site.urls)),
)

grazing/models.py
from django.db import models
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point


# Create your models here.
class State(models.Model):
    name = models.CharField(max_length=30)
    abbr = models.CharField(max_length=2)

    def __str__(self):
        return self.name

# not using NEPAType
class NEPAType(models.Model):
    name = models.CharField(max_length=255)
    abbr = models.CharField(max_length=4, null=True)

    def __str__(self):
        return self.name

# class Standard(models.Model):
#     name = models.CharField(max_length=255)
#
# class Cause(models.Model):
#     name = models.CharField(max_length=255)
#
#     def __str__(self):
#         return self.name

class FieldOffice(models.Model):
    state = models.ForeignKey("State")
    office_code = models.CharField(max_length=55)
    office_name = models.CharField(max_length=255)

    def __str__(self):
        return self.office_name

class Authorization(models.Model):
    number = models.CharField(max_length=55)

    def __str__(self):
        return self.number

class Operator(models.Model):
    # field_office = models.ForeignKey("FieldOffice")
    # auth_no = models.CharField(max_length=55, null=True)
    auth_no = models.ManyToManyField("Authorization")
    operator_display_name = models.CharField(max_length=255)
    address1 = models.CharField(max_length=255)
    address2 = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    st2 = models.CharField(max_length=255)
    zipcode15 = models.CharField(max_length=255)
    zipcode69 = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    release_text = models.CharField(max_length=255)

    def __str__(self):
        return self.operator_display_name

class Allotment(models.Model):

    # state = models.ForeignKey("State")
    field_office = models.ForeignKey("FieldOffice")
    allotment_number = models.CharField(max_length=11)
    allotment_unique = models.CharField(max_length=255)
    allotment_name = models.CharField(max_length=255)
    available_for_grazing = models.CharField(max_length=1)
    grazing_decision = models.CharField(max_length=255)
    public_acres = models.FloatField()
    amp_text = models.CharField(max_length=255)
    amp_implement_date = models.DateTimeField(null=True)
    management_stat_text = models.CharField(max_length=255)
    auth_no	= models.ManyToManyField("Authorization", null=True, blank=True)
    # following three fields are actually tied to permit rather than allotment
        #permitted_aums = models.IntegerField()
        #suspended_aums = models.IntegerField()
        #susp_use_temp = models.CharField(max_length=10)

    def __str__(self):
        return "Allotment name: {}, State: {}".format(self.allotment_name,  self.field_office.state)

class Permit(models.Model):

    field_office = models.ForeignKey("FieldOffice")
    auth_no = models.ForeignKey("Authorization")
    pl_effect_dt = models.DateTimeField()
    pl_exp_dt = models.DateTimeField()
    permit_status = models.CharField(max_length=50)
    allotment = models.ForeignKey("Allotment")
    livestock_number = models.FloatField()
    livestock_kind = models.CharField(max_length=25)
    pd_beg_dt = models.DateTimeField()
    pd_end_dt = models.DateTimeField()
    type_use = models.CharField(max_length=50)
    pl_percent = models.FloatField()
    aums = models.FloatField()

    def __str__(self):
        return self.auth_no.operator_display_name


class Health(models.Model):

    #field_office = models.ForeignKey("FieldOffice") # Is this really necessary if its already tied to allotment?
    allotment = models.ForeignKey("Allotment", null=True)
    allotment_name = models.CharField(max_length=255, null=True)
    allotment_unique = models.CharField(max_length=55, null=True)
    ### not using ... In Excel Files from BLM ... ###
        # auth_no = models.ForeignKey("Authorization") # Is this really necessary if its already tied to allotment?
        # land_health_eval_date = models.DateTimeField(null=True,blank=True) # Date of Most Recent Land Health Evaluation Report (mm/dd/yyyy)1
        # causal_factors_date = models.DateTimeField(null=True,blank=True) #Date of most recent Determination of Causal Factor(s) (mm/dd/yy
        # livestock_factor = models.NullBooleanField()
        # description = models.TextField(null=True)
        # cause_not_met = models.ForeignKey("Cause")
        # nepa_type = models.ForeignKey("NEPAType") #Type of NEPA Analysis for Grazing Authorization (EA, EIS, CX, D
        # nepa_date = models.DateTimeField(null=True,blank=True) #Date NEPA Analysis Completed (mm/dd/yyyy)5
        # nepa_identifier = models.CharField(max_length=55) #NEPA Identifier6
        # permit_status = models.CharField(max_length=55) #Permit or Lease Status
        # year_released = models.IntegerField(null=True) # 2012 or 2007 release from BLM to PEER/WWP?
    ### ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ###

    lhs2007 = models.CharField(max_length=255, null=True)
    lhs2012 =models.CharField(max_length=255, null=True)
    lhs = models.CharField(max_length=255, null=True)

    ### In shapefiles from Lattin
    ecoregion1 = models.CharField(max_length=255, null=True)
    ecoregion2 = models.CharField(max_length=255, null=True)
    ecoregion3 = models.CharField(max_length=255, null=True)
    geom = models.MultiPolygonField(srid=4326,null=True)  # Adjust SRID accordingly
    objects = models.GeoManager()

    def __str__(self):
        return self.allotment_name

########################################################################################################################
# vvvvvvvvvv Defunct vvvvvvvvvv
class Boundary(models.Model):
    allotment = models.ForeignKey("Allotment", null=True)  # Link this to our allotments, looks like some will not have a match
    allotment_name = models.CharField(max_length=255, null=True) # for boundaries that don't have an allotment entry in our db
    # allotment_number = models.CharField(max_length=55, null=True) # for boundaries that don't have an allotment entry in our db
    allotment_unique = models.CharField(max_length=255, null=True) # for boundaries that don't have an allotment entry in our db
    state = models.CharField(max_length=2, null=True) # for boundaries that don't have an allotment entry in our db
    geom = models.MultiPolygonField(srid=4326)  # Adjust SRID accordingly
    objects = models.GeoManager()
    def __str__(self):
        return "Allotment Boundary: " + self.allotment_name

grazing/views.py
from __future__ import division
from datetime import date
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.db.models import Sum
from django.db.models import Count

from django.contrib.gis.db import models
from django.contrib.gis.geos import *


from grazing.models import *

def index(request):


	states = State.objects.all().order_by('name')

	acreage = State.objects.aggregate(Sum('fieldoffice__allotment__public_acres'))

	all_permits = State.objects.aggregate(total=Count('fieldoffice__permit'))
	exempted_permits = State.objects.filter(fieldoffice__permit__permit_status='FLPMA 402(C)(2)/APPROP ACT').aggregate(total=Count('fieldoffice__permit'))
	exempted_permit_pct = (exempted_permits['total'] / all_permits['total']) * 100

	return render(request, 'base.html', {'states': states, 'acreage': acreage, 'exempted_permit_pct': exempted_permit_pct})

# state by state view, used to generate the descriptions used on the index page of the published graphic
def state(request, state_slug):

	thisyear = date.today().year

	state = State.objects.get(abbr=state_slug)

	#total acres
	acreage = State.objects.filter(abbr=state_slug).aggregate(total=Sum('fieldoffice__allotment__public_acres'))

	#total livestock, using aums
	# using total livestock will overcount because permit schedule lists twice, impossible to parse unique livestock count
	livestock = Permit.objects.filter(field_office__state__abbr=state_slug).aggregate(total=Sum('aums'))

#	State.objects.filter(abbr=state_slug).aggregate(total=Sum('fieldoffice__permit__livestock_number'))

	#total ranchers
	ranchers = Operator.objects.filter(auth_no__permit__field_office__state__abbr=state_slug).aggregate(total=Count('id'))
#	State.objects.filter(abbr=state_slug).aggregate(total=Count('fieldoffice__permit__auth_no__operator'))

	#permit renewals
	#pl_exp_dt__gte=thisyear
	all_permits = Permit.objects.filter(field_office__state__abbr=state_slug).aggregate(total=Count('auth_no', distinct = True))
	exempted_permits = Permit.objects.filter(field_office__state__abbr=state_slug, permit_status='FLPMA 402(C)(2)/APPROP ACT').aggregate(total=Count('auth_no', distinct = True))

	# all_permits = State.objects.filter(abbr=state_slug)
	# exempted_permits = State.objects.filter(abbr=state_slug, fieldoffice__permit__permit_status='FLPMA 402(C)(2)/APPROP ACT').aggregate(total=Count('fieldoffice__permit'))
	exempted_permit_pct = (exempted_permits['total'] / all_permits['total']) * 100 # hack to get this into readable pct format

	# acres meeting lhs, acres not evaluated

	lhs_acres_yes = Allotment.objects.filter(field_office__state__abbr=state_slug, health__lhs='ALL STANDARDS MET').aggregate(total=Count('public_acres'))
	lhs_filter_categories = ['NO DATA', 'DETERMINATION NOT COMPLETE', '----']
	lhs_acres_unk = Allotment.objects.filter(field_office__state__abbr=state_slug, health__lhs__in=lhs_filter_categories).aggregate(total=Sum('public_acres'))

	allotment_count = Allotment.objects.filter(field_office__state__abbr=state_slug).aggregate(total=Count('id', distinct=True))
	allotments_meeting_standards = Allotment.objects.filter(field_office__state__abbr=state_slug, health__lhs='ALL STANDARDS MET').aggregate(total=Count('id', distinct=True))
	allotments_not_evaluated = Allotment.objects.filter(field_office__state__abbr=state_slug, health__lhs__in=lhs_filter_categories).aggregate(total=Count('id', distinct=True))

	pct_meeting_standard = (allotments_meeting_standards['total'] / allotment_count['total']) * 100
	pct_not_evaluated = (allotments_not_evaluated['total'] / allotment_count['total']) * 100


	return render(request, 'state_detail.html', {
	'state': state,
	'acreage': acreage,
	'livestock': livestock,
	'ranchers': ranchers,
	'all_permits': all_permits,
	'exempted_permits': exempted_permits,
	'exempted_permit_pct': exempted_permit_pct,
	'lhs_acres_yes': lhs_acres_yes,
	'lhs_acres_unk': lhs_acres_unk,
	'allotment_count': allotment_count,
	'allotments_meeting_standards': allotments_meeting_standards,
	'allotments_not_evaluated': allotments_not_evaluated,
	'pct_meeting_standard': pct_meeting_standard,
	'pct_not_evaluated': pct_not_evaluated
	})


def allotment(request, allotment_unique):

	boundary = get_list_or_404(Health, allotment_unique=allotment_unique)[0] #.distinct()
	# Health.objects.filter(allotment_unique=allotment_unique)[0] #.distinct()

	allot = Allotment.objects.filter(allotment_unique=allotment_unique)

	total_acres = Allotment.objects.filter(allotment_unique=allotment_unique).aggregate(total=Sum('public_acres'))

	ranchers = Allotment.objects.filter(allotment_unique=allotment_unique).aggregate(total=Count('auth_no__operator__id'))

	permits = Permit.objects.filter(allotment__allotment_unique=allotment_unique)
	all_permits = Permit.objects.filter(allotment__allotment_unique=allotment_unique).aggregate(total=Count('auth_no', distinct = True))

	exempted_permits = Permit.objects.filter(allotment__allotment_unique=allotment_unique, permit_status='FLPMA 402(C)(2)/APPROP ACT').aggregate(total=Count('auth_no', distinct = True))
	# exempted_permit_pct = (exempted_permits['total'] / all_permits['total']) * 100 # hack to get this into readable pct format



	operators = Operator.objects.filter(auth_no__permit__allotment__allotment_unique=allotment_unique).distinct()

	# auths = allot.auth_no.all()

	# health = allot.health_set.all()

	return render(request, 'allotment_detail.html',
		{
		'allot': allot,
		# 'auths': auths,
		# 'health': health,
		'operators': operators,
		'boundary': boundary,
		'total_acres': total_acres,
		'ranchers': ranchers,
		'permits': permits,
		'all_permits': all_permits,
		'exempted_permits': exempted_permits,
		# 'exempted_permit_pct': exempted_permit_pct,

			})

grazing/templates/allotment_detail.html
{% extends "base.html" %}

{% load humanize %}
{% load grazingtemplates %}

{% block content %}

<style>

h3 {
  margin-top: -0.5em;
  margin-bottom: 1em;
}

h4 {
	color: #414243 !important;
  line-height: 3em;
}

h5 {
  font-weight: bold;
}

h6 {
  margin-top:1em;
  font-size: 1.25em;
}

p {
		font-size: 1.05em !important;
  	font-family: Georgia,Times,Times New Roman,serif;
}

small {
  color: #414243 !important;
}

.rancher {
  font-size: 0.85em !important;
}

.map-container {
  background-color: #f4f4f2;
}

.map-tease {
  font-size: 0.8em !important;
  font-family: Helvetica;
}

</style>

<div class="row">
  <div class="small-12 medium-11 medium-offset-1 columns">
    {% if allot %}
      {% for allot in allot %}
        <h6><small><em>{% if allot.field_office.state.abbr == 'OR' %}OREGON/WASHINGTON {% elif allot.field_office.state.abbr == 'MT' %} MONTANA/DAKOTAS {% else %} {{ allot.field_office.state|upper }}{% endif %}</em></small></h6>
      <h3>The {{ allot.allotment_name|title }} allotment spans {{ total_acres.total|floatformat|intcomma }} acres</h3>
      {% endfor %}
    {% else %}
      {% if boundary.allotment_name %}
        {% if boundary.allotment_name == 'N/A' %}
        <h6><small><em></em></small></h6>
        <h3>This allotment is unnamed</h3>
        {% else %}
        <h6><small><em></em></small></h6>
        <h3>The {{ boundary.allotment_name|title }} allotment</h3>
        {% endif %}
      {% else %}
        <h6><small><em></em></small></h6>
        <h3>This allotment is unnamed</h3>
      {% endif %}
    {% endif %}
  </div>
</div>
<div class="row">


  <div class="small-12 medium-5 medium-offset-1 columns end">
    <h5>Allotment health and management</h5>

    <p>



      <!-- Rangeland Health Standards -->
      As of 2013, the most recent year of available data, this grazing allotment
      {% if boundary.lhs == 'NOT MET - LIVESTOCK' or boundary.lhs == 'NOT MET - NOT LIVESTOCK' or boundary.lhs == 'NOT MET - NOTLIVESTOCK' or boundary.lhs == 'NOT MET - INSUFFICIENT INFORMATION' %}
        did not meet rangeland health standards in its last evaluation.
        {% if boundary.lhs == 'NOT MET - LIVESTOCK' %} Livestock grazing was cited as a factor. {% else %} Current livesotck grazing was not cited as a factor.
        {% endif %}
      {% elif boundary.lhs == 'ALL STANDARDS MET' %}
        was meeting rangeland health standards.
      {% elif boundary.lhs == 'DETERMINATION NOT COMPLETE' or boundary.lhs == '----' %}
        had not been evaluated for BLM's rangeland health standards.
      {% endif %}





    </p>

    <p>
    <!-- Allotment Management Plans -->
    {% if allot %}
        {% if allot.management_stat_text == 'IMPROVE CATEGORY' %}
          The BLM categorizes this allotment as needing to improve.
        {% else %}
        {% endif %}
        {% if allot.amp_text %}
          Unlike many, this grazing allotment has an allotment management plan that sets long-term goals for rangeland improvement and outlines specific monitoring plans. It was implemented in {{ allot.amp_implement_date.year }}.
        {% else %}
        {% if allot.management_stat_text == 'IMPROVE CATEGORY' %}
          However, it
        {% else %}
         The BLM
        {% endif %}
           has no listed allotment management plan, which would set long-term goals for rangeland improvement and outline specific monitoring plans.
        {% endif %}
    {% else %}
      BLM data shows no record of an allotment management plan for this allotment.
    {% endif %}
    </p>

    <h5>Who uses this allotment</h5>

{% if ranchers.total > 0 %}
    <p> {{ ranchers.total|apnumber|title }} {% if ranchers.total > 1 %}ranches use{% else %} ranch uses {% endif %} this land.
    <!-- Permit exemptions  -->
    {% if all_permits.total == 1 %}
      The one permit issued for this allotment was {% if exempted_permits.total > 0 %} {% else %} not {% endif %} renewed under a provision in federal law that exempts permits from environmental review.
    {% else %}
      Of the {{ all_permits.total|apnumber }} permits issued for this allotment, {% if exempted_permits.total > 0  and exempted_permits.total == all_permits.total and exempted_permits.total > 3 %} all {% endif %} {% if exempted_permits.total > 0 %} {{ exempted_permits.total|apnumber }} {% else %} none {% endif %} were renewed under a provision in federal law that exempts permits from environmental review.
    {% endif %}
    </p>

    <div class="row">
      <div class="small-10 small-offset-1">
        <ul>
          {% for o in operators %}
          <li>
            <b>{{ o|title }}</b> based in {{o.city|title}}, {{o.st2}} grazes up to
              {% for a in o.auth_no.all %}
                    {% for p in a.permit_set.all %}
                    {% if p.allotment.allotment_unique == boundary.allotment_unique %}

                  {% if p.pl_exp_dt.year >= 2016 %}

                    {{ p.livestock_number|floatformat|intcomma }} {{ p.livestock_kind|lower }}
                    {% if p.pd_end_dt.month == p.pd_beg_dt.month %}
                      in {{ p.pd_end_dt.month|month_name }}
                    {% else %}
                      between {{ p.pd_beg_dt.month|month_name }} and {{ p.pd_end_dt.month|month_name }}{% endif %}{% if forloop.last %}{% else %}{% if forloop.revcounter = 2 %} and {% else %},{% endif %}{% endif %}
                  {% else %}
                  {% endif %}

                    {% endif %}
                  {% endfor %}

                </li>
              {% endfor %}

          {% if not forloop.last %}<hr />{% endif %}
        {% endfor %}
        <ul>
      </div>
    </div>

    {% else %}
    <p>There are no current permits in the BLM database for this allotment.</p>
    {% endif %}
  </div>



  <div class="small-12 medium-5 columns end map-container">
    <div id="map"></div>
    <h5>Explore from above</h5>
    <p class="map-tease">Everything in the white border is an allotment managed by the the BLM. Zoom in to take a look through the land. Rangeland ecologists look for vegetation patterns, streamside erosion and other things when evaluating rangeland health.</p>

  <script type="text/javascript">
    var map = L.map('map').setView([{{boundary.geom.centroid.y }}, {{boundary.geom.centroid.x }}],

    {% if boundary.allotment.public_acres > 100000 %}
    9
    {% elif boundary.allotment.public_acres > 100000 %}
    10
    {% elif boundary.allotment.public_acres > 10000 %}
    11
    {% elif boundary.allotment.public_acres > 1000 %}
    12
    {% else %}
    13
    {% endif %}

    );

    // ESRI OPEN TILES
    L.esri.basemapLayer('Imagery').addTo(map);


    var AllotmentBoundary = {{ boundary.geom.geojson|safe }}

    var AllotmentStyle = {
          weight: 3,
          opacity: 1,
          color: 'white',
          fillOpacity: 0,
          // fillColor: getColor(feature.properties.LHS_CLASS)
      }

    L.geoJson( AllotmentBoundary, {
      style: AllotmentStyle
    }).addTo(map);

    map.touchZoom.disable();
    map.scrollWheelZoom.disable()

  </script>
</div>
</div>
{% endblock %}

grazing/templates/base.html
<!doctype html>
<html>
<head>

  <meta charset="utf-8">
   <title></title>
   <meta name="description" content="">
   <meta name="viewport" content="width=device-width, initial-scale=1">

   <!-- <link rel="stylesheet" href="css/style.css" /> -->
   <script type="text/javascript" src="http://opb-news-interactives.s3.amazonaws.com/lib/pym.js"></script>

   <!-- SWITCH FROM CDN TO OPB HOST BEFORE YOU PUSH? -->
   <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>

   <!-- Load Esri Leaflet from CDN -->
   <script src="http://cdn-geoweb.s3.amazonaws.com/esri-leaflet/1.0.0-rc.6/esri-leaflet.js"></script>

   <!-- DON'T FORGET YOUR GEOGRAPHY JSON FILES  -->
   <!-- <script src="js/yourgeography.geojson"></script> -->

   <!-- Using Foundation, for now ... -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.1.2/foundation.min.css" />
   <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.1.2/foundation.min.js"></script>

   <style type="text/css">

     html {
       padding: 0;
       margin: 0;
     }

     body {
       margin: 0;
       padding: 0;
     }

     #map {
       height: 400px;
       width: 100%;
       margin-bottom: 1.5em;
       margin-top: 1.5em;
      }

     /*LEAFLET STYLE OVERRIDES*/

     .leaflet-popup-content-wrapper {
       background-color: #fff;
       border-radius: 3px;
     }

     .leaflet-popup-tip{
       background-color: #fff;
     }

     .leaflet-popup-content {
       font-size: 1.125em;
       color: #363636;
     }

     .leaflet-popup-content h4{
       font-size: 20px;
       line-height: 0;
     }

     .photo-box {
       height: 150px;
       width: 100%;
       border: 2px solid #ccc;
       margin-bottom: 1em;
       overflow: hidden;
     }

  </style>

</head>

<body>


{% block content %}

<div class="row">
  <p>{{ acreage }}</p>
  <p>{{ exempted_permit_pct }}</p>


  {% for s in states %}

  <div class="small-12 medium-3 large-3 columns end">

    <a href="/states/{{ s.abbr }}"><h6><b><em>{{ s.name|upper }}</em></b></h6> </a>
    <ul>
      <li>TK ranchers, TK million cattle</li>
      <li>TK% of rangeland considered healthy, TK% unknown</li>
      <li>TK permits renewed without review</li>
    </ul>
      <div class="photo-box">
      <a href="/states/{{ s.abbr }}"><img src="http://s3-us-west-2.amazonaws.com/opb-news-interactives/earthfix/rangeland/{{ s.abbr|lower }}.png" /></a>
    </div>


  </div>

  {% endfor %}
</div>

{% endblock %}

</body>

</html>

grazing/templates/state_detail.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}

<a href="{% url "index" %}"> <<< HOME </a>
<div class="row">
  <div class="small-12 columns end">
    <h1> {{ state.name }} </h1>
    <ul>
      <li><strong>{{ acreage.total|floatformat|intword }} </strong> acres of BLM land here are used for grazing.
      <li>As of 2013, an estimated<strong> {{ pct_meeting_standard|floatformat:0 }}% </strong> of areas used for grazing met federal benchmarks for rangeland health.  An estimated <strong>{{ pct_not_evaluated|floatformat:0 }}% </strong> had not been evaluated.</li>
      <li>At least <strong>{{ ranchers.total|floatformat|intcomma }}</strong> ranches manage an estimated <strong>{{ livestock.total|floatformat|intword|intcomma }}</strong> in </strong> in <span data-tooltip aria-haspopup="true" class="has-tip" data-disable-hover='false' data-options="clickOpen: true;" tabindex=1 title="An animal unit month, or AUM, is the amount of forage needed to sustain one cow and her calf, one horse, or five sheep or goats for a month.">animal unit months</span></li>
      <li>Nearly <strong>{{ exempted_permit_pct|floatformat:0 }}%</strong> of grazing permits here were issued without a full environmental review </li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="small-12 medium-12 large-12 columns end">
    <div id="map"></div>
  </div>
</div>

<script src="https://s3-us-west-2.amazonaws.com/opb-news-interactives/earthfix/rangeland/{{ state.abbr|lower }}.geojson"></script>
<script type="text/javascript">

state_centroids = {
AZ:[33.7712,-111.3877],
CA:[36.1700,-119.7462],
CO:[39.0646,-105.3272],
ID:[44.2394,-114.5103],
MT:[46.9048,-110.3261],
NM:[34.8375,-106.2371],
NV:[38.4199,-117.1219],
OR:[44.5672,-122.1269],
WY:[42.7475,-107.2085],
UT:[40.1135,-111.8535]
}

  var map = L.map('map').setView(state_centroids["{{ state.abbr }}"], 7);

  // ESRI OPEN TILES
    L.esri.basemapLayer('Gray').addTo(map);

  // LAYER OPTIONS
    // Topographic
    // Streets
    // National Geographic
    // Oceans
    // Gray
    // Dark Gray
    // Imagery
    // Shaded Relief

  // OPEN STREET MAP BASE TILE
    // L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png').addTo(map);

  // MAP QUEST OPEN TILES
    // L.tileLayer('http://otile1.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.png').addTo(map);
    // L.tileLayer('http://otile1.mqcdn.com/tiles/1.0.0/sat/{z}/{x}/{y}.png').addTo(map);

  // STAMEN
    // L.tileLayer('http://tile.stamen.com/toner/{z}/{x}/{y}.png').addTo(map);
    // L.tileLayer('http://tile.stamen.com/terrain/{z}/{x}/{y}.png').addTo(map);
    // L.tileLayer('http://tile.stamen.com/watercolor/{z}/{x}/{y}.png').addTo(map);


    // MAKE THE TANK LAYER
    function getColor(d) {
        return d == 'ALL STANDARDS MET' ? '#a6d96a' :
               d == 'NOT MET - LIVESTOCK' ? '#d7191c' :
               d == 'NOT MET - NOT LIVESTOCK'  ? '#fdae61' :
               d == 'NOT MET - NOTLIVESTOCK'  ? '#fdae61' :
               d == 'NOT MET - INSUFFICIENT INFORMATION'  ? '#fdae61' :
               d == 'NO DATA'  ? 'black' :
               d == 'CLOSED'  ? 'black' :
               d ==  'DETERMINATION NOT COMPLETE'  ? 'black' :
                          'black';
    }

    function allotment_style(feature) {

        return {
          weight: 0.25,
          opacity: 1,
          color: 'white',
          fillOpacity: 1,
          fillColor: getColor(feature.properties.LHS_CLASS)
        };

      }

    function onEachFeature(feature, layer) {
        // does this feature have a property named popupContent?
        if (feature.properties && feature.properties.STALLOT) {
            layer.bindPopup("Dig deeper on this allotment. <a href='/allotments/" + feature.properties.STALLOT + "'>Click here! </a>");
        }
    }

  L.geoJson( allotment_boundaries, {
    style: allotment_style,
    onEachFeature: onEachFeature,
  }).addTo(map);

  // Disable drag and zoom handlers.
    map.touchZoom.disable();
    map.scrollWheelZoom.disable();

  // Disable tap handler, if present.
    if (map.tap) map.tap.disable();

</script>

{% endblock %}